const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUIweGlScUtXekphaXlocFpJVktnOEhubmJQT3c5d3BIZ1lhSTJHR3pIQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ1NhV2pMZFd5TnJuLy96aW1yUHk3VHp0cnVGWlNOQlBCdWs1ZGJWVEdBOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJPTzhiejBBSmJqYk5JZ1FKV3FWQlBNb3JoQVVETlFjeUtWRVZlN3lnbkdVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBSHhnSERWd1lSbmZwcnpZQ3UrNDBUbXdXQ0tNWnpHSHY3bTVVQjk4aGhJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkVJMHEvTTNSdkpJZWxZdkh1cXorZzFDbk4zS1BrU1pDczZRL1JxLzlRVkU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpKYnN6WGM3NFRXZmpLWThEMUZ1WVlsVWZkNjEvdktBMGh5MktBcm5sRms9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUpPUml5NEF3eHlXanAxS3hFMTE0WVNva2tGOXNybS9VaVJ6WGd4Z1oyMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRlNCTXBiTTNFTVVaeFVrZkZaaHZQVmlCajdRYXVNaEl4a1NvUWV0RUYxdz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjdQdElPdEszL29FVitobzZBQ2xjOUxSSkN5eS9nTk1NaDFSNDVQemw1eFNNc0NpTSswd2ppYmI2VjZKMjdEbFVrekNJTWtLRTRTd1JWY0JJQTB5MGl3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjM3LCJhZHZTZWNyZXRLZXkiOiJ0ZUcyeUkvaXlBN3h6TlZycnMvOWZSREVCdHh0QThFK1lodDR2MHFxZmFFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzUsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozNSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJSMDdPVnE4b1FQbWphVWR5WnlIc1dnIiwicGhvbmVJZCI6IjZhZDA0YWI1LWZkMWItNDBhYS04Nzg2LWQ2Njc2YzkzM2U4MSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDSGJnSlI0VWJ3eVVCcmQ1b2xaM2hrSkNHVUk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMTlUWjRBMWhUUXFvN1BrOFNIOVpOSXE0TEJvPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkZRN1BNUkVOIiwibWUiOnsiaWQiOiIyMjE3NzgyNzEzMTU6NzJAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2Qi/CdkI7wnZCR8J2QgyDwnZG+8J2RtvCdkbPwnZGtIPCdkbMu8J2Rs/CdkbbwnZKA8J2RqyDwnZGo8J2RtfCdkbbwnZG18J2SgPCdkbTwnZG28J2RvPCdkbog8J2Rs/CdkajwnZG18J2Rq/CdkazwnZG5IPCdkbXwnZKAIPCdka/wnZGo8J2Rq/CdkazwnZG6wrLCuSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSkMrbGFvREVNQ3EyN3NHR0JJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoicGxVUVRWQW5JWWhaTEZTY2IrU1orYVM3ZWI5UVFKbTBrNGNCK0wrS3VSST0iLCJhY2NvdW50U2lnbmF0dXJlIjoiQ2x3VEZCcTFQT2RxRzdReTNQZWpBb3AwY3h2aUdzRVhCOWxKTEpYNlZQVE5YRjg4Q2tCamFQckxXSElrY1lZS2cvMTBSV2g0ZDRodXVlWEYvZGNzQnc9PSIsImRldmljZVNpZ25hdHVyZSI6IktLdGdGam9KRTlhVmVrSk52c2x5RUVMYnZHNmN0c0huL21xaEdPUU9xaTJ3NVRVTFJxd1NXRDFpYTZzTysvcTVENllvK0VjWlhkeUxSUGhzVDhFZmhRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjIxNzc4MjcxMzE1OjcyQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmFaVkVFMVFKeUdJV1N4VW5HL2ttZm1rdTNtL1VFQ1p0Sk9IQWZpL2lya1MifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU4NDExMDEsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRmZQIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
